name: Monthly Composer Update

on:
  schedule:
    - cron:  '0 2 1 * *'  # El día 1 de cada mes a las 2am UTC
  workflow_dispatch:       # Permite ejecutarlo manualmente

jobs:
  composer-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install Composer dependencies
        run: composer install
      - name: Update Composer dependencies
        run: composer update
      - name: Commit updated composer.lock
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add composer.lock
          git commit -m "Monthly Composer update [Automated]" || echo "No changes to commit"
          git push origin HEAD:monthly-update || true
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Monthly Composer dependencies update"
          body: "Automated update of Composer dependencies."
          branch: monthly-update
